### ISSUE TITLE
Download failed:  Key not found in database

### ISSUE THREAD

**Issue by ghost** [agencyenterprise/filecoin-retrieval-browser-extension#114]
<img width="760" alt="Filecoin_Retrieval" src="https://user-images.githubusercontent.com/225111/98182945-44b3f600-1ec4-11eb-8680-73ab1c0e901c.png">

**Steps to Reproduce**
1.  Get the current browser extension and make sure to use `wsEndpoint` = `"wss://retrievalproxy.browser-retrieval.filecoin.io:443"`
2.  Retrieve this from storage miner:

 - `CID`: `bafykbzacecp5ijz6n2hoy6nwferyxajnnftfny52kntbmqv5ywo734yivekw4 `
 - `Miner`: `f019243`

3.  The retrieval should not take too long since it will be in the `files` cache on `retrievalproxy.browser-retrieval.filecoin.io`.  The total bytes of this CID are `4194304`.
4.  However, the blue download arrow will not work and will give the message shown above `Download failed:  Key not found in database`

**Comment by ghost** [comment]
The file is ~4 MB and I get multiple blocks in the IndexedDB after downloading:

<img width="999" alt="Screen Shot 2020-11-04 at 5 44 16 PM" src="https://user-images.githubusercontent.com/225111/98183455-62ce2600-1ec5-11eb-9f3f-62bc4347ae9b.png">

**Comment by brunolm** [comment]
CID with different parameters than what we have hard coded:
https://cid.ipfs.io/#bafykbzacecp5ijz6n2hoy6nwferyxajnnftfny52kntbmqv5ywo734yivekw4

Source code of this website above that decodes the CID:
https://github.com/multiformats/cid-utils-website

Hard coded part that needs to receive parameters from the decoded CID:
https://github.com/filecoin-shipyard/browser-retrieval/blob/57360727c142399f0560df10848c9a1787ab0c49/src/background/socket-client/SocketClient.js#L105

We need:
- CID version (`0` or `1`)
- Hash algorithm (`sha256` or `blake2b-256`)
- rawLeaves (`true` if multicodec = `raw`; `undefined` otherwise)

```
{
  cidVersion: 1 | 0,
  hashAlg: 'blake2b-256' | 'sha256',
  rawLeaves: true | undefined
}
```

UPDATE:

```js
format = decoded.codec
rawLeaves = decoded.codec === 'raw'

this.datastore.putContent(this.importSink, { cidVersion: decode.version, hashAlg: decode.hashAlg, format, rawLeaves });
```

**Comment by ghost** [comment]
We're still broken on `dag-pb` CIDs.  Examples:  `bafykbzaceb7xzlm65omwugcavfxxcxclhnwamjbcodz5rz4kbyhenq7m4pivg`, `bafykbzacecp5ijz6n2hoy6nwferyxajnnftfny52kntbmqv5ywo734yivekw4 `

<img width="738" alt="Screen Shot 2020-11-09 at 8 07 20 AM" src="https://user-images.githubusercontent.com/225111/98558433-a37dc480-2262-11eb-9e95-226e8276e394.png">

**Comment by ghost** [comment]
@aistoc Here are some CIDs that **do** work:

 - bafk2bzacebhlhbcnhmvover42qq5bx773c522skieho6nhtbz7d2ow3f4sw24
 - bafk2bzaced3qzrjfppals7u5kkxfdrpfxlwiyqa6q2w47hvfhbapg5em32irc

Here are some CIDs that **do not** work:

 - bafykbzaceb7xzlm65omwugcavfxxcxclhnwamjbcodz5rz4kbyhenq7m4pivg
 - bafykbzacecp5ijz6n2hoy6nwferyxajnnftfny52kntbmqv5ywo734yivekw4

When I say that it "works" or not, I am talking about the blue download arrow after the transfer finishes.  You can see in the code how we are generating the link for that icon.
